receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - zipkin
      processors:
        - batch
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - prometheus
      processors:
        - batch