spring:
  cloud:
    stream:
      # default:
      #   error-handler-definition: errorHandler
      function:
        definition: consumer
      bindings:
        consumer-in-0:
          destination: consumer
          group: observation-group
          content-type: application/json
          binder: kinesis
        producer-out-0:
          destination: consumer
          group: observation-group
          content-type: application/json
          binder: kinesis
      kinesis:
        binder:
          auto-create-stream: false
          kpl-kcl-enabled: true
          enable-observation: true
          checkpoint:
            table: checkpoint-table
          locks:
            table: locks-table
          headers:
            - test
    aws:
      stack.auto: false
      region:
        static: us-east-1
      credentials:
        access-key: foo
        secret-key: bar

logging.level:
  com.amazonaws.util.EC2MetadataUtils: error
  com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error