spring:
  cloud:
    function:
      definition: producer;consumer
    stream:
      default:
        error-handler-definition: errorHandler
      bindings:
        error:
          destination: errorHandler
        consumer-in-0:
          destination: demo-consumer
          group: observation-group
          content-type: application/json
          binder: kinesis
        producer-out-0:
          destination: demo-consumer
          group: observation-group
          content-type: application/json
          binder: kinesis
      kinesis:
        binder:
          kpl-kcl-enabled: true
          enable-observation: true
          headers:
            - test
    aws:
      stack.auto: false
      region:
        static: us-east-1
      credentials:
        access-key: foo
        secret-key: bar

logging.level:
  com.amazonaws.util.EC2MetadataUtils: error
  com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error